### ISSUE TITLE
Latest version of the exe does not include decimal after VIDEO_EXTRA_DELAY variable

### ISSUE THREAD

**Issue by SilverDeoxys563** [ercdndrs/AutoMaxLair#100]
![image](https://user-images.githubusercontent.com/36336402/111830694-b49ba980-88c4-11eb-8f48-55e38e972f50.png)

The latest version of the exe (from https://github.com/PokemonAutomation/AutoMaxLair/actions/runs/666597063) doesn't automatically append the 0.0 to the base value for the variable that prefills when launching it for the first time, and the mouse-over tooltip for that dialog box doesn't explicitly say that a decimal is required either. The config.sample.toml does specify the necessity of the decimal point (.) though, however.

**Comment by pifopi** [comment]
It's more of an issue with the config file. The decimal isn't required
