### ISSUE TITLE
Notification Level Shiny Only Ping Legendary Does not work as intended

### ISSUE THREAD

**Issue by db2810** [ercdndrs/AutoMaxLair#109]
The above notification level does not work as intended and instead sends notifications for each run instead of notifications for shinies and pings for legendaries

**Comment by db2810** [comment]
Running latest beta as of 03-26 version 0.8 beta 3-19-21

**Comment by ercdndrs** [comment]
Added in the [ComputerControl ](https://github.com/PokemonAutomation/ComputerControl)implementation.
