### ISSUE TITLE
Sometimes it gets stuck??

### ISSUE THREAD

**Issue by LordKurisu** [ercdndrs/AutoMaxLair#2]
I am not sure if its something I am doing wrong but sometimes it gets stuck on the screen where it determines what the opponent is, takes a capture like when it has found a shiny and quits.

Attached is a log of the last time it happened hopefully it will help
[Crash.txt](https://github.com/ercdndrs/AutoMaxLair/files/5792523/Crash.txt)

**Comment by ercdndrs** [comment]
It seems like there is sometimes a text encoding error when the script is trying to write to the log file. The error causes the button control thread to terminate, which signals the display thread to take a screenshot. Can you upload the log file for this run?

**Comment by LordKurisu** [comment]
[Yveltal_2021-01-10 08-42-17_log.txt](https://github.com/ercdndrs/AutoMaxLair/files/5792909/Yveltal_2021-01-10.08-42-17_log.txt)

**Comment by ercdndrs** [comment]
Ah unfortunately that doesn't give me any more information. What operating system are you using? I'm looking a bit more into why you might have an encoding error somewhere and I suspect it could be because of the default encoding specified by your OS.

**Comment by ercdndrs** [comment]
Also what version of Python are you using?

**Comment by ercdndrs** [comment]
One thing you could try is to change the following line in MaxLairInstance.log:
`with open(self.filename, 'a') as file:`
to:
`with open(self.filename, 'a', encoding='utf-8') as file:`

Please let me know if this works for you and I will make this change in the main file.

**Comment by LordKurisu** [comment]
ok im using windows 10 with python 3.7.2, i will try that modification and report back if i find anything.. thanks :)

**Comment by ercdndrs** [comment]
We have independently checked this solution and it seems to work, so I'm closing this issue.
