### ISSUE TITLE
Shiny hunt non legends

### ISSUE THREAD

**Issue by TeachingGame** [ercdndrs/AutoMaxLair#65]
Add an some additional lines to search for shiny non legends like regional forms. This could be done here

    if (
        not take_pokemon and (
            ctrlr.mode == 'strong boss' and 'weezing' in run.caught_pokemon)
        and ctrlr.check_sufficient_ore(1)
    ):
        reset_game = True
        ctrlr.log("Found weezing on this path.", "DEBUG")
        
    # After checking all the Pokemon, wrap up the run (including taking a
    # Pokemon or resetting the game, where appropriate).

**Comment by pifopi** [comment]
Will be fixed with #98

**Comment by TeachingGame** [comment]
This has been addressed in PR #98
