### ISSUE TITLE
overvaluing Wide Guard against rental mons

### ISSUE THREAD

**Issue by Naru-GoodLurker** [ercdndrs/AutoMaxLair#68]
Hitmonlee spent 5 wide guards on Vanillish (1st stage) and 4 wg on Kadabra (2nd stage). I don't know if other chosen mons with wide guard will do the same but I think it might be safe to save wide guard until boss round imo.

**Comment by ercdndrs** [comment]
A robust fix to this issue would involve planning the entire run, which is not necessary with the current state of the AI.
